spring:
  profiles: mysql
  datasource:
      url: jdbc:mysql://localhost:3306/medical_helper?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: jaeho
      password: jaeho1
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  batch:
    job:
      names: ${job.name:NONE}
